deploy:
  # image: ubuntu:22.04
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SSH_USER@$SSH_HOST "
      cd "~/todo-bot-prod" &&
      git pull &&
      docker login -u $GHCR_USER -p $GHCR_PASSWORD ghcr.io &&
      docker pull ghcr.io/tirth-bhagwat/todo-bot:latest &&
      docker compose up -d"
