version: "3.1"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo-db
    ports:
      - "5430:5432"
    networks:
      - bot-netw
    expose:
      - "5432"
    volumes:
      - /home/ubuntu/Projects/todo-bot-1/db_data/prod/data:/var/lib/postgresql/data

  todo-bot:
    image: todo-bot:latest
    networks:
      - bot-netw
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}

networks:
  bot-netw:
    driver: bridge
