version: "3.1"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo-db
    ports:
      - "6543:5432"
    networks:
      - bot-netw
    expose:
      - "5432"

  todo-bot:
    image: todo-bot:latest
    networks:
      - bot-netw
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/todo-db
      - TELOXIDE_TOKEN=6043871025:AAEZkYQutC1pO56V0pCEDhRVw7Ch8O6KxtI

networks:
  bot-netw:
    driver: bridge
