version: "3.1"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo-db
    ports:
      - "6543:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@vs.code"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_DISABLE_POSTFIX: "true"
      PGADMIN_LISTEN_PORT: "8080"
    ports:
      - "8080:8080"
